name: parqueadero_2025_g2
description: Proyecto Flutter de ejemplo
publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.6.1
  http: ^1.1.0
  provider: ^6.0.5
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.0.15
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12
  
  # To-Do App dependencies
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.3
  connectivity_plus: ^6.0.5
  uuid: ^4.4.0
  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/